In [1]:
import numpy as np

In [2]:
ls1 = [1,2,3]
print(type(ls1))
arr = np.array(ls1)
print(type(arr))
display(arr)

<class 'list'>
<class 'numpy.ndarray'>


array([1, 2, 3])

In [15]:
ls2 = [[1,2,3],[4,5,6]]
print(type(ls2))
arr2 = np.array(ls2)
print(type(arr2))
display(arr2)

<class 'list'>
<class 'numpy.ndarray'>


array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
arr3 = np.array([[1,2,6],[4,5,'a']])
arr3

array([['1', '2', '6'],
       ['4', '5', 'a']], dtype='<U11')

متد arange 
یک لیست درست میکند از شماره شروع تا انتها با استپ مشخص شده


In [42]:
print(np.arange(1,10))
print(np.arange(1,10,2))


[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


درست کردن و پرکردن یک ارایه با صفر یا یک
سطر و ستون آرایه باید داخل یک پرانتز قرار بگیرد

In [3]:
print(np.zeros(3),"\n\n")
print(np.zeros((3,3)),"\n\n")


print(np.ones(2),"\n\n")
print(np.ones((2,3)),"\n\n")

[0. 0. 0.] 


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 


[1. 1.] 


[[1. 1. 1.]
 [1. 1. 1.]] 




متد linspace
مقادیر ورودی : شروع ، پایان ، تعداد نقطه
ین تابع یک نقطه شروع و پایان میگیرد و تعداد نقاط این تعداد نقاط رو با فاصله مساوی بین شروع و پایان قرار میدهد . 
نکته : خود نقطه شروه و پایان جزو تعداد نقاط فاصله حساب میشوند
li = np.linspace(0,10,3)
بین 0 تا 10 را به دو قسمت مساوی تقسیم میکند

In [54]:
li = np.linspace(0,10,6)
display(li)

array([ 0.,  2.,  4.,  6.,  8., 10.])

درست کردن و پرکردن یک آرایه با مقدار رندم بین 0 تا 1
 درست کردن و پرکردن یک ماتریس با مقدار رندم بین 0 تا 1

-------------

یک عدد رندم بین دو عدد
یک آرایه رندم با طول مشخص بین دو عدد
یک ماتریس با سطر و ستون مشخص پر شده با عداد رندم بین دو عدد


In [63]:
display(np.random.rand(2))
display(np.random.rand(3,2))

display(np.random.randint(1,20))
display(np.random.randint(1,20,10))
display(np.random.randint(1,20,(2,3)))

array([0.31485136, 0.23176529])

array([[0.67335795, 0.89236039],
       [0.22961393, 0.97910799],
       [0.79287637, 0.34963235]])

5

array([ 2, 14, 18, 17, 14, 11, 13, 12,  5, 18])

array([[ 1, 10, 16],
       [13, 10, 14]])

تعریف یک آرایه یک بعدی و تبدیل آن به یک ماتریس

In [70]:
arr1 = np.arange(1,25)
arr1 = arr1.reshape(4,6)
arr1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

یک عدد رندم بین 0 تا 100

In [5]:
np.random.randint(1,100)

96

ده عدد رندم بین 20 تا 50

In [16]:
arr2 = np.random.randint(20,50,10)
display(arr2)
print("max Number is: {} in position:{}".format(arr2.max(),arr2.argmax()))
print(f"min Number is: {arr2.min()} in position:{arr2.argmin()}")
arr2[0]

array([25, 26, 40, 23, 45, 43, 23, 23, 44, 46])

max Number is: 46 in position:9
min Number is: 23 in position:3


25

ماتریس مربعی با قطر 1

In [4]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])